language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
  - brew update
  - brew remove --force xctool
  - brew install xctool --HEAD
  
script: 'xctool --version;xcodebuild -project PersistentObject.xcodeproj -scheme PersistentObject -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,name=iPhone 6" build test'
